import 'dotenv/config';

export const config = {
  PORT: Number(process.env.PORT) || 4000,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
  OLLAMA_HOST: process.env.OLLAMA_HOST || 'http://localhost:11434',
  DEFAULT_MODEL_PROVIDER: process.env.DEFAULT_MODEL_PROVIDER || 'gemini', // 'gemini' | 'ollama'
  DEFAULT_GEMINI_MODEL: process.env.DEFAULT_GEMINI_MODEL || 'gemini-2.5-flash',
  DEFAULT_OLLAMA_MODEL: process.env.DEFAULT_OLLAMA_MODEL || 'qwen2.5',
  GROQ_API_KEY: process.env.GROQ_API_KEY || '',
  DEFAULT_GROQ_MODEL: process.env.DEFAULT_GROQ_MODEL || 'llama-3.3-70b-versatile',
  AGENT_SECRET_TOKEN: process.env.AGENT_SECRET_TOKEN || '',
  NESTJS_API_URL: process.env.NESTJS_API_URL || 'http://localhost:3000/api',
  CONTEXT_WINDOW_MAX_INPUT_TOKENS: Number(process.env.CONTEXT_WINDOW_MAX_INPUT_TOKENS) || 12000,
  CONTEXT_WINDOW_OUTPUT_RESERVE_TOKENS: Number(process.env.CONTEXT_WINDOW_OUTPUT_RESERVE_TOKENS) || 2000,
  CONTEXT_WINDOW_HISTORY_RETENTION_RATIO: Number(process.env.CONTEXT_WINDOW_HISTORY_RETENTION_RATIO) || 0.8,
  CONTEXT_WINDOW_TOOL_RESULT_MAX_CHARS: Number(process.env.CONTEXT_WINDOW_TOOL_RESULT_MAX_CHARS) || 6000,
  CONTEXT_WINDOW_TOOL_RESULTS_MAX_TOTAL_CHARS: Number(process.env.CONTEXT_WINDOW_TOOL_RESULTS_MAX_TOTAL_CHARS) || 12000,
  CONTEXT_WINDOW_SUMMARY_MAX_CHARS: Number(process.env.CONTEXT_WINDOW_SUMMARY_MAX_CHARS) || 1200,
};
